CREATE TABLE 'informix'.xref_info
       (object_ref CHAR(128) NOT NULL,
       object_ref_type CHAR(128) NOT NULL,
       event CHAR(128) NOT NULL,
       referenced_in CHAR(128) NOT NULL,
       ref_in_type CHAR(128) NOT NULL,
       pbl CHAR(128) NOT NULL,
       application CHAR(64) NOT NULL,
       scope CHAR(1) NOT NULL) ;
 
ALTER TABLE informix.xref_info ADD CONSTRAINT ( PRIMARY KEY (
       object_ref,
       object_ref_type,
       event,
       referenced_in,
       ref_in_type,
       pbl,
       application,
       scope
       ) CONSTRAINT primary ) ;
 
INSERT INTO 'informix'.pbcattbl
       (pbt_tnam,
        pbt_tid,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
           VALUES
       ('xref_info',
        0,
        'informix',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
       'Cross Reference Detail') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('xref_info',
        'informix',
        'object_ref',
        'Reference Name:',
        0,
        'Reference~r~nName',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
        '',
        'The object or class referenced') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('xref_info',
        'informix',
        'object_ref_type',
        'Reference Type:',
        0,
        'Reference~r~nType',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
        '',
        'The class type of the reference') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('xref_info',
        'informix',
        'event',
        'Referenced From:',
        0,
        'Referenced~r~nFrom',
        0,
        23,
        '',
        0,
        65,
        659,
        '',
        'N',
        '',
        '',
        'Where the reference is made') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('xref_info',
        'informix',
        'referenced_in',
        'Object Reference In:',
        0,
        'Object~r~nReferenced~r~nIn',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
        '',
        'Object containing the reference') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('xref_info',
        'informix',
        'ref_in_type',
        'Refer. In Type',
        0,
        'Refer. In ~r~nType',
        0,
        23,
        '',
        0,
        65,
        330,
        '',
        'N',
        '',
        '',
        'The class type for the Referenced In') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('xref_info',
        'informix',
        'pbl',
        'Library:',
        0,
        'Library',
        0,
        23,
        '',
        0,
        65,
        659,
        '',
        'N',
        '',
        '',
        'The path and filename for the library containing the referenced class') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('xref_info',
        'informix',
        'application',
        'Application:',
        0,
        'Application',
        0,
        23,
        '',
        0,
        65,
        330,
        '',
        'N',
        '',
        '',
        'The name of the application object') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('xref_info',
        'informix',
        'scope',
        'Scope:',
        0,
        'Scope',
        0,
        23,
        '',
        0,
        65,
        165,
        '',
        'N',
        '',
        '',
        'The scope of the reference ( G or O )') ;
 
CREATE TABLE 'informix'.app_classes
       (application CHAR(64) NOT NULL,
       pbl CHAR(255) NOT NULL,
       object CHAR(50) NOT NULL,
       nestedclass CHAR(255) NOT NULL,
       parent CHAR(255) NOT NULL,
       parenttypeof CHAR(50) NOT NULL,
       scope CHAR(1) NOT NULL,
       nestedin CHAR(255) NOT NULL,
       isreferenced INTEGER) ;
 
ALTER TABLE informix.app_classes ADD CONSTRAINT ( PRIMARY KEY (
       application,
       pbl,
       object,
       nestedclass,
       parent,
       parenttypeof,
       nestedin
       ) CONSTRAINT primary ) ;
 
INSERT INTO 'informix'.pbcattbl
       (pbt_tnam,
        pbt_tid,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
           VALUES
       ('app_classes',
        0,
        'informix',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
       'Class information for the Cross Reference Report') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'application',
        'Application:',
        0,
        'Application',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
        '',
        'The name of the application object') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'pbl',
        'Pbl:',
        0,
        'Pbl',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
        '',
        'The path and filename for the library containing the object') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'object',
        'Object:',
        0,
        'Object',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
        '',
        'The base object containing the class reference') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'nestedclass',
        'Nested Class:',
        0,
        'Nested~r~nClass',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
        '',
        'The nested class ( could be controlname, function, event, variable, etc. ) ') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'parent',
        'Parent:',
        0,
        'Parent',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
        '',
        'The name of the parent of the nested class') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'parenttypeof',
        'Parent TypeOf:',
        0,
        'Parent~r~nTypeOf',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
        '',
        'The type of the parent class') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'scope',
        'Scope:',
        0,
        'Scope',
        0,
        23,
        '',
        0,
        65,
        69,
        '',
        'N',
        '',
        '',
        'The object scope ( G or O ) ') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'nestedin',
        'Nested In:',
        0,
        'Nested~r~nIn',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
        '',
        'The name of the class this is nested in') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_classes',
        'informix',
        'isreferenced',
        'Is Referenced:',
        0,
        'Is~r~nReferenced',
        0,
        24,
        '[General]',
        0,
        65,
        165,
        '',
        'N',
        '',
        '',
        'An indicator that the class was referenced in the application') ;
 
CREATE TABLE 'informix'.app_info
       (application CHAR(64) NOT NULL,
       report_globals INTEGER NOT NULL,
       list_sql INTEGER NOT NULL,
       list_sp INTEGER NOT NULL,
       list_ps_func INTEGER NOT NULL,
       list_all_events INTEGER NOT NULL,
       list_controls INTEGER NOT NULL,
       sort CHAR(256) NOT NULL,
       rep_date DATE NOT NULL,
       rep_time DATETIME HOUR TO FRACTION(5) NOT NULL,
       pbl CHAR(64)) ;
 
ALTER TABLE informix.app_info ADD CONSTRAINT ( PRIMARY KEY (
       application
       ) CONSTRAINT primary ) ;
 
INSERT INTO 'informix'.pbcattbl
       (pbt_tnam,
        pbt_tid,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
           VALUES
       ('app_info',
        0,
        'informix',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
       'Application Header information') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'application',
        'Application:',
        0,
        'Application',
        0,
        23,
        '',
        0,
        65,
        654,
        '',
        'N',
        '',
        '',
        'The name of the application object') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'report_globals',
        'Report Globals:',
        0,
        'Report~r~nGlobals',
        0,
        24,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
        '',
        'Report Globals Only option') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'list_sql',
        'List Sql:',
        0,
        'List~r~nSql',
        0,
        24,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
        '',
        'List SQL References option') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'list_sp',
        'List SP:',
        0,
        'List~r~nSP',
        0,
        0,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
        '',
        'List stored procedure references option') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'list_ps_func',
        'List PS Functions:',
        0,
        'List PS~r~nFunctions',
        0,
        24,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
        '',
        'List Powerscript function references option') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'list_all_events',
        'List Events:',
        0,
        'List~r~nEvents',
        0,
        24,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
        '',
        'List all events option') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'list_controls',
        'List Controls:',
        0,
        'List~r~nControls',
        0,
        0,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
        '',
        'List control references option') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'sort',
        'Sort:',
        0,
        'Sort',
        0,
        23,
        '',
        0,
        65,
        654,
        '',
        'N',
        '',
        '',
        'Sort Sequence') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'rep_date',
        'Report Date:',
        0,
        'Report~r~nDate',
        0,
        23,
        '',
        0,
        65,
        252,
        '',
        'N',
        '',
        '',
        'Date report was created') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'rep_time',
        'Report Time:',
        0,
        'Report~r~nTime',
        0,
        23,
        '',
        0,
        65,
        252,
        '',
        'N',
        '',
        '',
        'Time report was created') ;
 
INSERT INTO 'informix'.pbcatcol
        (pbc_tnam,
        pbc_ownr,
        pbc_cnam,
        pbc_labl,
        pbc_lpos,
        pbc_hdr,
        pbc_hpos,
        pbc_jtfy,
        pbc_mask,
        pbc_case,
        pbc_hght,
        pbc_wdth,
        pbc_ptrn,
        pbc_bmap,
        pbc_init,
        pbc_edit,
        pbc_cmnt)
       VALUES
       ('app_info',
        'informix',
        'pbl',
        'Library:',
        0,
        'Library',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
        '',
        'The path and filename of the library for the application') ;
