CREATE TABLE DBA."APP_INFO"
       ("APPLICATION" CHAR(64) NOT NULL,
       "REPORT_GLOBALS" NUMBER(1,0) NOT NULL,
       "LIST_SQL" NUMBER(1,0) NOT NULL,
       "LIST_SP" NUMBER(1,0) NOT NULL,
       "LIST_PS_FUNC" NUMBER(1,0) NOT NULL,
       "LIST_ALL_EVENTS" NUMBER(1,0) NOT NULL,
       "LIST_CONTROLS" NUMBER(1,0) NOT NULL,
       "SORT" CHAR(255) NOT NULL,
       "REP_DATE" DATE NOT NULL,
       "REP_TIME" DATE NOT NULL,
       "PBL" VARCHAR(64)) ;
 
 
ALTER TABLE DBA."APP_INFO" ADD ( CONSTRAINT primary PRIMARY KEY (
       "APPLICATION"
       )) ;
 
INSERT INTO .pbcattbl(
        pbt_tnam,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
        VALUES
       ('APP_INFO',
        'DBA',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
       'Application Header information') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'APPLICATION',
        'Application:',
        0,
        'Application',
        0,
        23,
        '',
        0,
        65,
        654,
        '',
        'N',
        '',
       '',
       'The name of the application object') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'REPORT_GLOBALS',
        'Report Globals:',
        0,
        'Report~r~nGlobals',
        0,
        24,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
       '',
       'Report Globals Only option') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'LIST_SQL',
        'List Sql:',
        0,
        'List~r~nSql',
        0,
        24,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
       '',
       'List SQL References option') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'LIST_SP',
        'List SP:',
        0,
        'List~r~nSP',
        0,
        0,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
       '',
       'List stored procedure references option') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'LIST_PS_FUNC',
        'List PS Functions:',
        0,
        'List PS~r~nFunctions',
        0,
        24,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
       '',
       'List Powerscript function references option') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'LIST_ALL_EVENTS',
        'List Events:',
        0,
        'List~r~nEvents',
        0,
        24,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
       '',
       'List all events option') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'LIST_CONTROLS',
        'List Controls:',
        0,
        'List~r~nControls',
        0,
        0,
        '',
        0,
        65,
        206,
        '',
        'N',
        '',
       '',
       'List control references option') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'SORT',
        'Sort:',
        0,
        'Sort',
        0,
        23,
        '',
        0,
        65,
        654,
        '',
        'N',
        '',
       '',
       'Sort Sequence') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'REP_DATE',
        'Report Date:',
        0,
        'Report~r~nDate',
        0,
        23,
        '',
        0,
        65,
        252,
        '',
        'N',
        '',
       '',
       'Date report was created') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'REP_TIME',
        'Report Time:',
        0,
        'Report~r~nTime',
        0,
        23,
        '',
        0,
        65,
        252,
        '',
        'N',
        '',
       '',
       'Time report was created') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_INFO',
        'DBA',
        'PBL',
        'Library:',
        0,
        'Library',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
       '',
       'The path and filename of the library for the application') ;
 
COMMIT WORK ;
 
CREATE TABLE DBA."APP_CLASSES"
       ("APPLICATION" CHAR(64) NOT NULL,
       "PBL" CHAR(255) NOT NULL,
       "OBJECT" CHAR(50) NOT NULL,
       "NESTEDCLASS" CHAR(255) NOT NULL,
       "PARENT" CHAR(255) NOT NULL,
       "PARENTTYPEOF" CHAR(50) NOT NULL,
       "SCOPE" CHAR(1) NOT NULL,
       "NESTEDIN" CHAR(255) NOT NULL,
       "ISREFERENCED" NUMBER(1,0) ) ;
 
 
ALTER TABLE DBA."APP_CLASSES" ADD ( CONSTRAINT primary PRIMARY KEY (
       "APPLICATION",
       "PBL",
       "OBJECT",
       "NESTEDCLASS",
       "PARENT",
       "PARENTTYPEOF",
       "NESTEDIN"
       )) ;
 
INSERT INTO .pbcattbl(
        pbt_tnam,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
        VALUES
       ('APP_CLASSES',
        'DBA',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
       'Class information for the Cross Reference Report') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'APPLICATION',
        'Application:',
        0,
        'Application',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
       '',
       'The name of the application object') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'PBL',
        'Pbl:',
        0,
        'Pbl',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
       '',
       'The path and filename for the library containing the object') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'OBJECT',
        'Object:',
        0,
        'Object',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
       '',
       'The base object containing the class reference') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'NESTEDCLASS',
        'Nested Class:',
        0,
        'Nested~r~nClass',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
       '',
       'The nested class ( could be controlname, function, event, variable, etc. ) ') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'PARENT',
        'Parent:',
        0,
        'Parent',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
       '',
       'The name of the parent of the nested class') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'PARENTTYPEOF',
        'Parent TypeOf:',
        0,
        'Parent~r~nTypeOf',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
       '',
       'The type of the parent class') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'SCOPE',
        'Scope:',
        0,
        'Scope',
        0,
        23,
        '',
        0,
        65,
        69,
        '',
        'N',
        '',
       '',
       'The object scope ( G or O ) ') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'NESTEDIN',
        'Nested In:',
        0,
        'Nested~r~nIn',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
       '',
       'The name of the class this is nested in') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('APP_CLASSES',
        'DBA',
        'ISREFERENCED',
        'Is Referenced:',
        0,
        'Is~r~nReferenced',
        0,
        24,
        '[General]',
        0,
        65,
        165,
        '',
        'N',
        '',
       '',
       'An indicator that the class was referenced in the application') ;
 
COMMIT WORK ;
 
CREATE TABLE DBA."XREF_INFO"
       ("OBJECT_REF" CHAR(128) NOT NULL,
       "OBJECT_REF_TYPE" CHAR(128) NOT NULL,
       "EVENT" CHAR(128) NOT NULL,
       "REFERENCED_IN" CHAR(128) NOT NULL,
       "REF_IN_TYPE" CHAR(128) NOT NULL,
       "PBL" CHAR(128) NOT NULL,
       "APPLICATION" CHAR(64) NOT NULL,
       "SCOPE" CHAR(1) NOT NULL) ;
 
 
ALTER TABLE DBA."XREF_INFO" ADD ( CONSTRAINT primary PRIMARY KEY (
       "OBJECT_REF",
       "OBJECT_REF_TYPE",
       "EVENT",
       "REFERENCED_IN",
       "REF_IN_TYPE",
       "APPLICATION"
       )) ;
 
INSERT INTO .pbcattbl(
        pbt_tnam,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
        VALUES
       ('XREF_INFO',
        'DBA',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
        -8,
        400,
        'N',
        'N',
        0,
        34,
       'MS Sans Serif',
       'Cross Reference Detail') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('XREF_INFO',
        'DBA',
        'OBJECT_REF',
        'Reference Name:',
        0,
        'Reference~r~nName',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
       '',
       'The object or class referenced') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('XREF_INFO',
        'DBA',
        'OBJECT_REF_TYPE',
        'Reference Type:',
        0,
        'Reference~r~nType',
        0,
        23,
        '',
        0,
        65,
        878,
        '',
        'N',
        '',
       '',
       'The class type of the reference') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('XREF_INFO',
        'DBA',
        'EVENT',
        'Referenced From:',
        0,
        'Referenced~r~nFrom',
        0,
        23,
        '',
        0,
        65,
        659,
        '',
        'N',
        '',
       '',
       'Where the reference is made') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('XREF_INFO',
        'DBA',
        'REFERENCED_IN',
        'Object Reference In:',
        0,
        'Object~r~nReferenced~r~nIn',
        0,
        23,
        '',
        0,
        65,
        439,
        '',
        'N',
        '',
       '',
       'Object containing the reference') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('XREF_INFO',
        'DBA',
        'REF_IN_TYPE',
        'Refer. In Type',
        0,
        'Refer. In ~r~nType',
        0,
        23,
        '',
        0,
        65,
        330,
        '',
        'N',
        '',
       '',
       'The class type for the Referenced In') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('XREF_INFO',
        'DBA',
        'PBL',
        'Library:',
        0,
        'Library',
        0,
        23,
        '',
        0,
        65,
        659,
        '',
        'N',
        '',
       '',
       'The path and filename for the library containing the referenced class') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('XREF_INFO',
        'DBA',
        'APPLICATION',
        'Application:',
        0,
        'Application',
        0,
        23,
        '',
        0,
        65,
        330,
        '',
        'N',
        '',
       '',
       'The name of the application object') ;
 
INSERT INTO .pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('XREF_INFO',
        'DBA',
        'SCOPE',
        'Scope:',
        0,
        'Scope',
        0,
        23,
        '',
        0,
        65,
        165,
        '',
        'N',
        '',
       '',
       'The scope of the reference ( G or O )') ;
 
COMMIT WORK ;
