WHENEVER SQLERROR CONTINUE
spool &10

define HTABLESPACE1 = &1
define HTABLESPACE2 = &2
define HTABLESPACE3 = &3

define HFILE1 = &4
define HFILE2 = &5
define HFILE3 = &6

define HSIZE1 = &7
define HSIZE2 = &8
define HSIZE3 = &9

set heading off
set feedback off
set timing off
set verify off

REMARK *** FOR HARVEST META DATA
CREATE TABLESPACE &HTABLESPACE1 DATAFILE '&HFILE1' 
SIZE &HSIZE1 M AUTOEXTEND ON NEXT 5 M;

REMARK *** FOR HARVEST BLOBS
CREATE TABLESPACE &HTABLESPACE2 DATAFILE '&HFILE2'
SIZE &HSIZE2 M AUTOEXTEND ON NEXT 5 M;

REMARK *** FOR HARVEST INDEXES
CREATE TABLESPACE &HTABLESPACE3 DATAFILE '&HFILE3' 
SIZE &HSIZE3 M AUTOEXTEND ON NEXT 5 M;

commit;
spool off
exit






