SELECT 	
    B.ITEMOBJID, 
	I.ITEMNAME,
	B.BRANCHOBJID, 
	B.PACKAGEOBJID, 
	P.PACKAGENAME
FROM 	(SELECT B.ITEMOBJID FROM HRVSTUSER.HARBRANCH B, HRVSTUSER.HARITEMS I, HRVSTUSER.HARPACKAGE P WHERE B.ITEMOBJID=I.ITEMOBJID AND B.PACKAGEOBJID=P.PACKAGEOBJID AND P.PACKAGENAME = 'OnHold')
WHERE
	B.ITEMOBJID=I.ITEMOBJID AND
	B.PACKAGEOBJID=P.PACKAGEOBJID AND
    P.PACKAGENAME = 'UpdatesFromPOPs_Devl';