WHENEVER SQLERROR CONTINUE
SPOOL &2
SET FEEDBACK ON
SET TIMING OFF
SET VERIFY OFF

REM ***
REM *** Drop Tables for CMEW user
REM ***

DROP TABLE &1 .COUNTER CASCADE CONSTRAINTS;
DROP TABLE &1 .ECCM_CONFIGURATION CASCADE CONSTRAINTS;
DROP TABLE &1 .ECCM_USER CASCADE CONSTRAINTS;
DROP TABLE &1 .ENTERPRISE_PACKAGE CASCADE CONSTRAINTS;
DROP TABLE &1 .ENTERPRISE_PACKAGE_STATUS CASCADE CONSTRAINTS;
DROP TABLE &1 .ENTERPRISE_PACKAGE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE &1 .ECCM_ACTIONLOG CASCADE CONSTRAINTS;
DROP TABLE &1 .ECCM_LOG CASCADE CONSTRAINTS;
DROP TABLE &1 .ENTERPRISE_PACKAGE_SUBPACKAGE CASCADE CONSTRAINTS;
DROP TABLE &1 .HARVEST_SUBPACKAGE_ACTIONS CASCADE CONSTRAINTS;
DROP TABLE &1 .WORKBENCH_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE &1 .WORKBENCH_PROVIDER CASCADE CONSTRAINTS;
DROP TABLE &1 .PROVIDER_USER CASCADE CONSTRAINTS;
DROP TABLE &1 .SETTINGS CASCADE CONSTRAINTS;
DROP TABLE &1 .USER_PREFERENCES CASCADE CONSTRAINTS;

REM ***
REM *** Drop CMEW user
REM ***

DROP USER &1;

REM ***
REM *** Drop ECCMREADER user
REM ***

DROP USER ECCMREADER;

COMMIT;

SPOOL OFF;
EXIT;

