WHENEVER SQLERROR CONTINUE
SPOOL &3
SET FEEDBACK ON
SET TIMING OFF
SET VERIFY OFF

REM ***
REM *** Create Tablespace for CMEW user
REM ***

CREATE TABLESPACE DBO DATAFILE 'DBO.ORA' SIZE 8M AUTOEXTEND ON;
COMMIT;

REM ***
REM *** Create CMEW user
REM ***

CREATE USER &1  IDENTIFIED BY &2  DEFAULT TABLESPACE DBO PROFILE DEFAULT QUOTA UNLIMITED ON DBO ACCOUNT UNLOCK;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE ANY INDEX TO &1 ;

REM ***
REM *** Create User ECCMREADER 
REM ***

CREATE USER ECCMREADER IDENTIFIED BY ECCMREADER;
GRANT RESOURCE, CONNECT, CREATE SESSION, CREATE SYNONYM, SELECT ANY TABLE, ALTER SESSION TO ECCMREADER;

SPOOL OFF;
EXIT;

