WHENEVER SQLERROR CONTINUE
SPOOL &2
SET FEEDBACK ON
SET TIMING OFF
SET VERIFY OFF

REM ***
REM *** Grant ECCMREADER -Must be logged in as CMEW user
REM ***

GRANT SELECT ON &1 .ENTERPRISE_PACKAGE_SUBPACKAGE TO ECCMREADER;

SPOOL OFF;
EXIT;
