WHENEVER SQLERROR CONTINUE
SPOOL &2
SET FEEDBACK ON
SET TIMING OFF
SET VERIFY OFF
REM ***
REM *** Grant ECCMREADER -Must be logged in as Harvest Table Owner
REM ***
GRANT SELECT ON &1 .HARPACKAGE TO ECCMREADER;
GRANT SELECT ON &1 .HARENVIRONMENT TO ECCMREADER;
SPOOL OFF;
EXIT;
