WHENEVER SQLERROR CONTINUE
SPOOL &1
SET FEEDBACK ON
SET TIMING OFF
SET VERIFY OFF

REM ***
REM *** Upgrade r1.1 CMEW Tables 
REM ***

REM ***
REM *** Create ENTERPRISE_PACKAGE_STATUS table and alter ENTERPRISE_PACKAGE table
REM ***

CREATE TABLE ENTERPRISE_PACKAGE_STATUS ( EP_ID NUMBER(38) NOT NULL, ECCM_CONFIGURATIONID NUMBER(38) NOT NULL, EP_PKGSTATUS NUMBER(38) NOT NULL );

ALTER TABLE ENTERPRISE_PACKAGE_STATUS ADD CONSTRAINT PK_ENTERPRISE_PACKAGE_STATUS PRIMARY KEY (EP_ID);

CREATE INDEX NDX_ENT_PACKAGE_STATUS ON ENTERPRISE_PACKAGE_STATUS (EP_ID, ECCM_CONFIGURATIONID);

ALTER TABLE ENTERPRISE_PACKAGE ADD EP_EXEC_NOTIFICATION NUMBER(38) DEFAULT 0;

REM ***
REM *** Alter History Table to add eccm_configurationid column
REM ***

ALTER TABLE ENTERPRISE_PACKAGE_HISTORY ADD ECCM_CONFIGURATIONID NUMBER(38);

REM ***
REM *** Alter Table names 
REM ***

RENAME PROVIDER TO WORKBENCH_PROVIDER;

RENAME PRODUCT TO WORKBENCH_PRODUCT;

SPOOL OFF;
EXIT;

