d:
mkdir BuildDownloads
mkdir downloader
mkdir iSense
mkdir iSenseAgent
mkdir iSenseManager
mkdir iSenseRemote
mkdir iSenseRestore
mkdir iSenseTray
mkdir iXMedia
mkdir Main.DailyBuild
mkdir nbase
mkdir NBaseMigration
mkdir nchevron
mkdir nmap
mkdir NMC
mkdir Nucleus9
mkdir PowerGUI
mkdir RECYCLER
mkdir rubish
mkdir sdks
mkdir Security
mkdir TARGET
mkdir Temp
mkdir Test
mkdir TFS
mkdir TFSBuild_Source
mkdir TFS_Builds
mkdir TmpInclude
mkdir Tools
mkdir WAYNE
mkdir WayneDB
mkdir WORK