rem hco -b DEVSWA -en "CMEW Testing" -f "CMEW Testing" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "CMEW Testing.OUT"
rem hci -b HARDEV1 -en "CMEW Testing.arv"   -o "CMEW Testing.in"
REM hco -b PRODSWA -en "HarvestAdmin" -st "Development" -vp "\\" -br -usr xxxxxxxx -pw xxxxxxxx -s "*.*" -ced -op pc -eh hardev1.dfo -o deploy.txt
REM hci *.* -b HARDEV1 -en name -st name -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hco -b DEVSWA -en "CMEW Testing" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "CMEW Testing.OUT"
hco -b DEVSWA -en "Dev1" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Dev1.OUT"
hco -b DEVSWA -en "Dev2" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Dev2.OUT"
hco -b DEVSWA -en "Dev3" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Dev3.OUT"
hco -b DEVSWA -en "Dev4" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Dev4.OUT"
hco -b DEVSWA -en "Devl" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Devl.OUT"
hco -b DEVSWA -en "Harvest Training" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Harvest Training.OUT"
hco -b DEVSWA -en "Production" -st "Devl" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Production.OUT"
hco -b DEVSWA -en "XDevelopment" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "XDevelopment.OUT"
hco -b DEVSWA -en "Deployment" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Deployment.OUT"
hco -b DEVSWA -en "Release Model Test" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Release Model Test.OUT"
hco -b DEVSWA -en "MERGETEST" -st "DEV" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "MERGETEST.OUT"
hco -b DEVSWA -en "MikeNetVenom" -st "Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "MikeNetVenom.OUT"
hco -b DEVSWA -en "Retek Base Code" -st "Import" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Retek Base Code.OUT"
hco -b DEVSWA -en "Retek CR1 - Wave 2 Development" -st "CR1 Development" -vp "\\" -br -r -s "*.*" -ced -op pc -eh hardev1.dfo -o "Retek CR1 - Wave 2 Development.OUT"

echo Now do the check ins
pause

hci -b HARDEV1 -en "CMEW Testing" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Dev1" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Dev2" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Dev3" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Dev4" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Devl" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Harvest Training" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Production" -st "Devl" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "XDevelopment" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "DeploymentX" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Release Model Test" -st "Development" -p "DEVSWA reload" -vp "\Release\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -cp "C:\Documents and Settings\AndrewsMic\My Documents\harvest projects\Archives\Release" -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "MERGETEST"  -st "DEV" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "MikeNetVenom" -st "Development" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Retek Base Code" -st "Import" -p "DEVSWA reload" -vp "\\" -pn "CkIn" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"
hci -b HARDEV1 -en "Retek CR1 - Wave 2 Development" -st "CR1 Development" -p "DEVSWA reload" -vp "\\" -pn "Check In New and Existing Items" -ur -d -de "Reload from DEVDBS to HARDEV1" -s "*.*" -op pc -if ne -eh hardev1.dfo –oa "hardev1.reload"