xcopy /s/d/q/y s:\build\%1\*.vcproj  d:\%2\*.vcproj
xcopy /s/d/q/y s:\build\%1\*.vbproj  d:\%2\%1\*.vbproj
xcopy /s/d/q/y s:\build\%1\*.sln     d:\%2\%1\*.sln
xcopy /s/d/q/y s:\build\%1\*.h       d:\%2\*.h 
xcopy /s/d/q/y s:\build\%1\*.cpp  d:\%2\*.cpp 
xcopy /s/d/q/y s:\build\%1\*.c    d:\%2\*.c
xcopy /s/d/q/y s:\build\%1\*.ini  d:\%2\*.ini 
xcopy /s/d/q/y s:\build\%1\*.sql  d:\%2\*.sql
xcopy /s/d/q/y s:\build\%1\*.mak  d:\%2\*.mak
xcopy /s/d/q/y s:\build\%1\*.in   d:\%2\*.in
xcopy /s/d/q/y s:\build\%1\*.rc   d:\%2\*.rc
xcopy /s/d/q/y s:\build\%1\*.odl  d:\%2\*.odl
xcopy /s/d/q/y s:\build\%1\*.ctl  d:\%2\*.ctl
xcopy /s/d/q/y s:\build\%1\*.vbp  d:\%2\*.vbp
xcopy /s/d/q/y s:\build\%1\*.bas  d:\%2\*.bas
xcopy /s/d/q/y s:\build\%1\*.frm  d:\%2\*.frm
xcopy /s/d/q/y s:\build\%1\*.frx  d:\%2\*.frx
xcopy /s/d/q/y s:\build\%1\*.cls  d:\%2\*.cls

