get applbld.cmd
get applname.cmd
get basebld.cmd
get bldnotes.pl
get changes.lst
get chckparm.pl
get dailybuild.pl
get finishappl.cmd
get fndshare.cmd
get GetServer.cmd
get GetServerName.pl
get promote.cmd
get shdbgBuild.pl
