--
-- Copyright (c) 2002 Computer Associates inc. All rights reserved. 
--
WHENEVER SQLERROR CONTINUE
spool &4

define HARVESTMETATSNAME = &1
define HARVESTBLOBTSNAME = &2
define HARVESTINDEXTSNAME = &3

set heading off
set feedback off
set timing off
set verify off

REMARK *** FOR HARVEST META DATA
ALTER TABLESPACE &HARVESTMETATSNAME 
DEFAULT STORAGE ( MAXEXTENTS UNLIMITED);

REMARK *** FOR HARVEST BLOBS
ALTER TABLESPACE &HARVESTBLOBTSNAME DEFAULT STORAGE ( MAXEXTENTS UNLIMITED );

REMARK *** FOR HARVEST INDEXES
ALTER TABLESPACE &HARVESTINDEXTSNAME 
DEFAULT STORAGE ( MAXEXTENTS UNLIMITED);

spool off
exit






