WHENEVER SQLERROR CONTINUE;
spool &1;

CREATE INDEX HARALLCHILDRENPATH_CLD_IDX ON 
 HARALLCHILDRENPATH (CHILDITEMID)  TABLESPACE HARVESTINDEX;

ALTER TABLE HARTABLEINFO ADD(AUTHENTICATEUSER CHAR(1) DEFAULT 'Y' NOT NULL);

DROP INDEX HARASSOCPKG_IND;

CREATE INDEX HARASSOCPKG_IND2 
ON HARASSOCPKG (ASSOCPKGID ) 
TABLESPACE HARVESTINDEX;

ALTER TABLE HARPATHFULLNAME
MODIFY(PATHFULLNAME VARCHAR2(1024));


CREATE INDEX HARITEMACCESS_IND1 
ON HARITEMACCESS (USRGRPOBJID ) 
TABLESPACE HARVESTINDEX;

CREATE INDEX HARITEMACCESS_IND2 
ON HARITEMACCESS (VIEWACCESS ) 
TABLESPACE HARVESTINDEX;


ALTER TABLE HARHARVEST MODIFY (SECUREHARVEST DEFAULT 'N', 
ADMINUSER DEFAULT 'N',  VIEWUSER DEFAULT 'N', ADMINENVIRONMENT DEFAULT 'N',
VIEWENVIRONMENT DEFAULT 'N', ADMINREPOSITORY DEFAULT 'N', 
VIEWREPOSITORY DEFAULT 'N', ADMINFORMTYPE DEFAULT 'N', VIEWFORMTYPE DEFAULT 'N');

ALTER TABLE HARENVIRONMENTACCESS MODIFY (SECUREACCESS DEFAULT 'N', 
UPDATEACCESS DEFAULT 'N', EXECUTEACCESS DEFAULT 'N', VIEWACCESS DEFAULT 'N');

ALTER TABLE HARREPOSITORYACCESS MODIFY (SECUREACCESS DEFAULT 'N', 
UPDATEACCESS DEFAULT 'N',  VIEWACCESS DEFAULT 'N');

ALTER TABLE HARFORMTYPEACCESS MODIFY (SECUREACCESS DEFAULT 'N', 
UPDATEACCESS DEFAULT 'N',  VIEWACCESS DEFAULT 'N');


ALTER TABLE HARSTATEACCESS MODIFY (UPDATEACCESS DEFAULT 'N', 
UPDATEPKGACCESS DEFAULT 'N');

ALTER TABLE HARSTATEPROCESSACCESS MODIFY (EXECUTEACCESS DEFAULT 'N');

ALTER TABLE HARITEMACCESS MODIFY (VIEWACCESS DEFAULT 'Y');

spool off
EXIT