--
-- Copyright (c) 2002 Computer Associates inc. All rights reserved. 
--
WHENEVER SQLERROR EXIT FAILURE
--
-- Create BLOB tables
--
-- Accept previously calculated storage sizes
--SPOOL &7

DEFINE initext = &1
DEFINE nextext = &2
DEFINE initindex = &3
DEFINE nextindex = &4
DEFINE HARVESTBLOBTSNAME = &6
DEFINE HARVESTINDEXTSNAME = &5

CREATE TABLE harVersionData (
   VERSIONDATAOBJID NUMBER NOT NULL 
      CONSTRAINT harVersionData_pk PRIMARY KEY
      USING INDEX TABLESPACE &HARVESTINDEXTSNAME, 
   REFCOUNTER NUMBER DEFAULT 0  NOT NULL , 
   DATASIZE NUMBER NOT NULL , 
   COMPRESSED CHAR(1) NOT NULL , 
   COMPDATASIZE NUMBER DEFAULT 0  NOT NULL , 
   FILEACCESS CHAR(9) NULL, 
   MODIFYTIME DATE NULL, CREATETIME DATE NULL , 
   DCB VARCHAR2(256) NULL, TEXTFILE NUMBER NOT NULL , 
   ITEMOBJID NUMBER DEFAULT 0  NOT NULL,
   VERSIONDATA BLOB NULL)   
LOB(VERSIONDATA) STORE AS (  TABLESPACE &HARVESTBLOBTSNAME 
   STORAGE ( INITIAL &initext M NEXT &nextext M 
             MINEXTENTS 1 MAXEXTENTS 999 
             PCTINCREASE 0) 
   INDEX HARDATA_LOBINDEX
   ( STORAGE( INITIAL &initindex M NEXT &nextindex M
              MINEXTENTS 1 MAXEXTENTS 999
              PCTINCREASE 0) )
    NOCACHE NOLOGGING PCTVERSION 0 )
TABLESPACE &HARVESTBLOBTSNAME;
    
CREATE TABLE harVersionDelta (
	CHILDVERSIONDATAID NUMBER NOT NULL,
 	PARENTVERSIONDATAID NUMBER NOT NULL, 
	DELTASIZE NUMBER NOT NULL, 
	VERSIONDELTA BLOB NULL,  
	CONSTRAINT harVersionDelta_pk 
    PRIMARY KEY (CHILDVERSIONDATAID, PARENTVERSIONDATAID)
    USING INDEX TABLESPACE &HARVESTINDEXTSNAME
)
LOB(VERSIONDELTA) 
    STORE AS (  TABLESPACE &HARVESTBLOBTSNAME NOCACHE NOLOGGING PCTVERSION 0)
TABLESPACE &HARVESTBLOBTSNAME;


CREATE INDEX HARVERSIONDATA_ITEMID_IND
ON HARVERSIONDATA(ITEMOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

-- spool off
-- EXIT
