WHENEVER SQLERROR CONTINUE
spool &10


define HARVESTMETATSNAME = &1
define HARVESTBLOBTSNAME = &2
define HARVESTINDEXTSNAME = &3

define HARVESTMETAFILE = &4
define HARVESTBLOBFILE = &5
define HARVESTINDEXFILE = &6

define HARVESTMETAFILESIZE = &7
define HARVESTBLOBFILESIZE = &8
define HARVESTINDEXFILESIZE = &9

set heading off
set feedback off
set timing off
set verify off

REMARK *** FOR HARVEST META DATA
CREATE TABLESPACE &HARVESTMETATSNAME DATAFILE '&HARVESTMETAFILE' SIZE &HARVESTMETAFILESIZE M;

REMARK *** FOR HARVEST BLOBS
CREATE TABLESPACE &HARVESTBLOBTSNAME DATAFILE '&HARVESTBLOBFILE'
SIZE &HARVESTBLOBFILESIZE M AUTOEXTEND ON NEXT 5 M;

REMARK *** FOR HARVEST INDEXES
CREATE TABLESPACE &HARVESTINDEXTSNAME DATAFILE '&HARVESTINDEXFILE' SIZE &HARVESTINDEXFILESIZE M;

commit;
spool off
exit






