SELECT	HARITEMPATH.VIEWITEMPATH, HARPATHFULLNAME.PATHFULLNAME,
	HARITEM.ITEMNAME
FROM	HARENVIRONMENT,
	HARITEM,
	HARITEMPATH, HARPATHFULLNAME,
	HARVERSION
WHERE	HARENVIRONMENT.ENVOBJID = HARVERSION.ENVOBJID
AND	HARVERSION.ITEMOBJID = HARITEM.ITEMOBJID
AND HARITEM.PATHOBJID=HARITEMPATH.PATHOBJID AND	HARITEM.PATHOBJID = HARPATHFULLNAME.PATHOBJID
AND	HARENVIRONMENT.ENVIRONMENTNAME LIKE 'TIMS%'