SELECT	COUNT(HARITEM.ITEMNAME),
                HARPATHFULLNAME.PATHFULLNAME,
                HARENVIRONMENT.HARENVIRONMENTNAME
FROM	HARENVIRONMENT,
    HARITEM,
    HARPATHFULLNAME,
    HARVERSION
WHERE	HARENVIRONMENT.ENVOBJID = HARVERSION.ENVOBJID
AND	HARVERSION.ITEMOBJID = HARITEM.ITEMOBJID
AND	HARITEM.PATHOBJID = HARPATHFULLNAME.PATHOBJID
GROUP BY HARENVIRONMENT.HARENVIRONMENTNAME;
