/*
 *   indexes.sql
 */
--
-- Copyright (c) 2002 Computer Associates inc. All rights reserved. 
--
WHENEVER SQLERROR CONTINUE
DEFINE HARVESTINDEXTSNAME = &1
--

--
-- PR# 1062: DELETING A REPOSITORY, FOLDER, OR VERSION LOCKS THE DATABASE
--

CREATE INDEX HARITEMS_PARENTOBJID 
ON HARITEMS (ParentObjId) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX HARVERSIONDATA_ITEMOBJID 
ON HARVERSIONDATA (ItemObjId) 
TABLESPACE &HARVESTINDEXTSNAME;

--
--

--
-- PR# 1391: DELETE VERSION PROCESS DEGRADES AS NUMBER OF VERSIONS INCREASE
--

CREATE INDEX HARVERSIONS_MERGEDVERSIONID 
ON HARVERSIONS (MergedVersionId) 
TABLESPACE &HARVESTINDEXTSNAME;

--
--

--
-- PR# 1434: HARREFRESH QUERY TAKES LONG TIME
--

CREATE INDEX HARITEMS_REPOSITOBJID 
ON HARITEMS (RepositObjId) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX HARREPINVIEW_REPOSITOBJID 
ON HARREPINVIEW (RepositObjId)
TABLESPACE &HARVESTINDEXTSNAME;

--
--

CREATE INDEX HARALLCHILDRENPATH_CLD_IDX 
ON HARALLCHILDRENPATH (CHILDITEMID)  
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX "HARAPPRHIST_IND" ON "HARAPPROVEHIST" 
("PACKAGEOBJID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARAPPROVELIST_IND" ON "HARAPPROVELIST" 
("PROCESSOBJID" , "STATEOBJID" , "ISGROUP" , "USROBJID" , "USRGRPOBJID" ) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARASSOCPKG_IND" ON "HARASSOCPKG" 
("FORMOBJID" , "ASSOCPKGID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX "HARASSOCPKG_IND2" 
ON "HARASSOCPKG" ("ASSOCPKGID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARENVIRONMENT_IND" ON "HARENVIRONMENT" 
("ENVIRONMENTNAME" ) 
TABLESPACE &HARVESTINDEXTSNAME ;

CREATE UNIQUE INDEX "HARFORM_IND" ON "HARFORM" ("FORMNAME" , 
"FORMTYPEOBJID" )   
TABLESPACE &HARVESTINDEXTSNAME ;

CREATE INDEX "HARFORMHIST_IND" ON "HARFORMHISTORY" 
("FORMOBJID" ) TABLESPACE &HARVESTINDEXTSNAME ;

CREATE UNIQUE INDEX "HARFORMTYPE_IND" ON "HARFORMTYPE" 
("FORMTYPENAME" )   
TABLESPACE &HARVESTINDEXTSNAME ;

CREATE INDEX "HARFORMTYPEDEFS_IND" ON "HARFORMTYPEDEFS" 
("FORMTYPEOBJID" )  TABLESPACE &HARVESTINDEXTSNAME ;

CREATE UNIQUE INDEX "HARFORMTYPEDEF_ALT" ON "HARFORMTYPEDEFS" 
("FORMTYPEOBJID" , "COLUMNNAME" ) TABLESPACE &HARVESTINDEXTSNAME ;

CREATE UNIQUE INDEX "HARFORMTYPEDEF_COL" ON "HARFORMTYPEDEFS" 
("COLUMNNAME" ) TABLESPACE &HARVESTINDEXTSNAME ;

CREATE UNIQUE INDEX "P_UKEY" ON "HARITEMS" ("PARENTOBJID" , 
"ITEMNAME" ) TABLESPACE &HARVESTINDEXTSNAME ;

CREATE INDEX HARITEMS_IND_TYPE 
ON HARITEMS (ITEMTYPE,PARENTOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX HARITEMRELATIONSHIP_REFITM_IDX 
ON  HARITEMRELATIONSHIP (REFITEMID) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARLINKPROC_IND" ON "HARLINKEDPROCESS" 
("PARENTPROCOBJID" , "PROCESSNAME" ) 
TABLESPACE &HARVESTINDEXTSNAME ;

CREATE UNIQUE INDEX "HARNOTIFYLIST_IND" ON "HARNOTIFYLIST" 
("PROCESSOBJID" , "STATEOBJID" , "PARENTPROCOBJID" , "ISGROUP" , 
"USROBJID" , "USRGRPOBJID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARPACKAGE_IND" ON "HARPACKAGE" 
("PACKAGENAME" , "ENVOBJID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX HARPACKAGE_IND_ENV 
ON HARPACKAGE (ENVOBJID, STATEOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARPKGGRP_IND" ON "HARPACKAGEGROUP" 
("ENVOBJID" , "PKGGRPNAME" )  
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX "HARPKGHIST_IND" ON "HARPKGHISTORY" 
("PACKAGEOBJID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX "HARPKGSINPKGGRP_IND" ON "HARPKGSINPKGGRP" 
("PKGGRPOBJID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARREPOSITORY_IND" ON "HARREPOSITORY" 
("REPOSITNAME" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARSTATE_IND" ON "HARSTATE" 
("STATENAME", "ENVOBJID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARSTATEPROC_IND" ON "HARSTATEPROCESS" 
("STATEOBJID" , "PROCESSNAME" )  
TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARUSER_IND" ON "HARUSER" ("USERNAME" ) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARUSERGROUP_IND" ON "HARUSERGROUP" 
("USERGROUPNAME" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX "HARVIEW_NAME_IND" ON "HARVIEW" ("VIEWNAME" , 
"ENVOBJID" ) TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX "HARVERSIONS_PKG_IND" ON "HARVERSIONS" ("PACKAGEOBJID")  
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX "HARVERSIONS_ITEM_IND" ON "HARVERSIONS" ("ITEMOBJID")  
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX "HARVERSIONS_PAR_IND" ON "HARVERSIONS" ("PARENTVERSIONID")  
TABLESPACE &HARVESTINDEXTSNAME;
--
-- Recreate indexes on old View/Version tables
--
CREATE INDEX OLDHARALLCHILDRENPATH_IND
ON OLDHARALLCHILDRENPATH(PATHOBJID) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARCHECKOUT_IND1 
ON OLDHARCHECKOUT (VERSIONOBJID ) 
TABLESPACE &HARVESTINDEXTSNAME ;

CREATE INDEX OLDHARCHECKOUT_IND2 
ON OLDHARCHECKOUT (ITEMOBJID)  
TABLESPACE &HARVESTINDEXTSNAME ;

CREATE INDEX OLDHARENVREPOSITORY_IND
ON OLDHARENVREPOSITORY(ENVOBJID) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARITEM_IND
ON OLDHARITEM(PATHOBJID) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX OLDHARITEMPATH_IND
ON OLDHARITEMPATH(PATHNAME, PARENTPATHID) 
TABLESPACE &HARVESTINDEXTSNAME;

CREATE UNIQUE INDEX OLDHARREPOSITORY_IND
ON OLDHARREPOSITORY(REPOSITNAME)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARREPVIEWVERSION_IND1
ON OLDHARREPVIEWVERSION(REPVIEWOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARREPVIEWVERSION_IND2
ON OLDHARREPVIEWVERSION(ITEMOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARREPVIEWVERSION_IND3
ON OLDHARREPVIEWVERSION(VERSIONOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARVERSION_IND
ON OLDHARVERSION(PACKAGEOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARVERSION_IND2
ON OLDHARVERSION(ITEMOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARVERSION_IND3
ON OLDHARVERSION(ENVOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARVERSION_IND4
ON OLDHARVERSION(PARENTVERSIONID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARVERSIONINVIEW_IND
ON OLDHARVERSIONINVIEW(VERSIONOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARVIEWVERSION_IND1
ON OLDHARVIEWVERSION(VIEWOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARVIEWVERSION_IND2
ON OLDHARVIEWVERSION(ITEMOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX OLDHARVIEWVERSION_IND3
ON OLDHARVIEWVERSION(VERSIONOBJID)
TABLESPACE &HARVESTINDEXTSNAME;

CREATE INDEX HARITEMACCESS_IND1 
ON HARITEMACCESS (USRGRPOBJID ) 
TABLESPACE &HARVESTINDEXTSNAME;


CREATE INDEX HARVERSIONINVIEW_IND
ON HARVERSIONINVIEW(VERSIONOBJID)
TABLESPACE &HARVESTINDEXTSNAME;


create index harversions_dataid_ind 
on harversions( versiondataobjid )
TABLESPACE &HARVESTINDEXTSNAME;



