/* 
 * ValidateReferences.sql
 *
 * Drop and recreate foreign key constraints in order to validate 
 * references.
 */
--
-- Copyright (c) 2002 Computer Associates inc. All rights reserved. 
--
WHENEVER SQLERROR EXIT FAILURE

--
-- PR# 1029: Remove orphan and duplicate records
--

-- Remove package/form associations between packages and/or forms that no longer exist.

DELETE FROM HARASSOCPKG A
WHERE
NOT EXISTS (SELECT * FROM HARFORM F WHERE F.FormObjId = A.FormObjId) OR
NOT EXISTS (SELECT * FROM HARPACKAGE P WHERE P.PackageObjId = A.AssocPkgId);

-- Remove notifications associated with linked-processes and/or state-processes that no longer exist.

DELETE FROM HARNOTIFY N
WHERE
(N.ParentProcObjId IS NOT NULL AND NOT EXISTS
(SELECT * FROM HARLINKEDPROCESS L WHERE L.ParentProcObjId = N.ParentProcObjId AND L.ProcessObjId = N.ProcessObjId)) OR
(N.StateObjId IS NOT NULL AND NOT EXISTS
(SELECT * FROM HARSTATEPROCESS S WHERE S.StateObjId = N.StateObjId AND S.ProcessObjId = N.ProcessObjId));

-- Remove notification-list entries associated with linked-processes, state-processes, users and/or user-groups that no longer exist.

DELETE FROM HARNOTIFYLIST N
WHERE
(N.ParentProcObjId IS NOT NULL AND NOT EXISTS
(SELECT * FROM HARLINKEDPROCESS L WHERE L.ParentProcObjId = N.ParentProcObjId AND L.ProcessObjId = N.ProcessObjId)) OR
(N.StateObjId IS NOT NULL AND NOT EXISTS
(SELECT * FROM HARSTATEPROCESS S WHERE S.StateObjId = N.StateObjId AND S.ProcessObjId = N.ProcessObjId)) OR
(N.UsrObjId IS NOT NULL AND NOT EXISTS
(SELECT * FROM HARUSER U WHERE U.UsrObjId = N.UsrObjId)) OR
(N.UsrGrpObjId IS NOT NULL AND NOT EXISTS
(SELECT * FROM HARUSERGROUP G WHERE G.UsrGrpObjId = N.UsrGrpObjId));

-- Remove UDPs associated with linked-processes and/or state-processes that no longer exist.

DELETE FROM HARUDP U
WHERE
(U.ParentProcObjId IS NOT NULL AND NOT EXISTS
(SELECT * FROM HARLINKEDPROCESS L WHERE L.ParentProcObjId = U.ParentProcObjId AND L.ProcessObjId = U.ProcessObjId)) OR
(U.StateObjId IS NOT NULL AND NOT EXISTS
(SELECT * FROM HARSTATEPROCESS S WHERE S.StateObjId = U.StateObjId AND S.ProcessObjId = U.ProcessObjId));

-- Remove form history entries associated with forms that no longer exist.

DELETE FROM HARFORMHISTORY H
WHERE
NOT EXISTS (SELECT * FROM HARFORM F WHERE F.FormObjId = H.FormObjId);

-- Remove duplicates from HarApproveHist.

DELETE FROM HARAPPROVEHIST WHERE ROWID NOT IN 
(
SELECT MIN(ROWID)
FROM HARAPPROVEHIST
GROUP BY EnvObjId, StateObjId, PackageObjId, UsrObjId, ExecDTime, Action
);

-- Add missing HarFormHistory creation entries using <SuperUser> and <CurrentDateTime> as Creator and Creation DateTime.

INSERT INTO HARFORMHISTORY (FormObjId, UsrObjId, ExecDTime, Action)
SELECT F.FormObjId, 1, SYSDATE, 'Created'
FROM HARFORM F
WHERE NOT EXISTS (SELECT * FROM HARFORMHISTORY H WHERE F.FormObjId = H.FormObjId AND H.Action = 'Created');

-- Update HarFormHist NULL values using <SuperUser> and/or <CurrentDateTime> as Creator and Creation DateTime.

UPDATE HARFORMHISTORY 
SET UsrObjId = DECODE(UsrObjId, NULL, 1, UsrObjId), ExecDTime = DECODE(ExecDTime, NULL, SYSDATE, ExecDTime)
WHERE Action = 'Created' AND ((UsrObjId IS NULL) OR (ExecDTime IS NULL));

--
--

--
-- Drop all foreign key constraints
--
START off.sql
SPOOL DropConstraintSlave.sql
SELECT 'alter table ' || table_name || ' drop constraint ' || constraint_name ||
          ';'
  FROM user_constraints
 WHERE constraint_type = 'R';
SPOOL off

SPOOL FormConstraintsSlave.sql
SELECT 'ALTER TABLE ' ||
       RTRIM(formtablename) ||
       ' ADD CONSTRAINT harFormTbl_' ||
       formtypeobjid ||
       '_FK ' ||
'FOREIGN KEY (formobjid) REFERENCES harForm(formobjid) ON DELETE CASCADE;' 
FROM harFormType;
spool off

SET termout on
SET echo on
SET feedback on
SPOOL ValidateReferences.log
START DropConstraintSlave.sql


ALTER TABLE HARALLCHILDRENPATH ADD CONSTRAINT HACP_1
 FOREIGN KEY (PATHOBJID)
  REFERENCES HARITEMPATH(PATHOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARALLCHILDRENPATH ADD CONSTRAINT HACP_2
 FOREIGN KEY (CHILDPATHOBJID)
  REFERENCES HARITEMPATH(PATHOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARAPPROVE ADD CONSTRAINT HARAPPROVE_SPID_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARAPPROVEHIST ADD CONSTRAINT HARAPPRHIST_EID_FK
 FOREIGN KEY (ENVOBJID)
  REFERENCES HARENVIRONMENT(ENVOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARAPPROVELIST ADD CONSTRAINT HARAPPLST_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARAPPROVELIST ADD CONSTRAINT HARAPPLST_UGID_FK
 FOREIGN KEY (USRGRPOBJID)
  REFERENCES HARUSERGROUP(USRGRPOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARAPPROVELIST ADD CONSTRAINT HARAPPLST_USRID_FK
 FOREIGN KEY (USROBJID)
  REFERENCES HARUSER(USROBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARASSOCFORM ADD CONSTRAINT HARASSOCFRM_FID_FK
 FOREIGN KEY (FORMOBJID)
  REFERENCES HARFORM(FORMOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARASSOCPKG ADD CONSTRAINT HARASSOCPKG_FID_FK
 FOREIGN KEY (FORMOBJID)
  REFERENCES HARFORM(FORMOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARCHECKINPROC ADD CONSTRAINT HARCIPROC_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARCHECKOUT ADD CONSTRAINT HARCKOUT_FORPKG_FK
 FOREIGN KEY (FORPKGID)
  REFERENCES HARPACKAGE(PACKAGEOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARCHECKOUT ADD CONSTRAINT HARCKOUT_VERID_FK
 FOREIGN KEY (VERSIONOBJID)
  REFERENCES HARVERSION(VERSIONOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARCHECKOUTPROC ADD CONSTRAINT HARCOPROC_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/

ALTER TABLE HARCONMRGPROC ADD CONSTRAINT CMP_SPID_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARCRPKGPROC ADD CONSTRAINT HARCRPKG_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARCRSENVMRGPROC ADD CONSTRAINT CEMP_SPID_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/

ALTER TABLE HARDELVERSPROC ADD CONSTRAINT HARDVPROC_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARDEMOTEPROC ADD CONSTRAINT HARDEM_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARENVREPOSITORY ADD CONSTRAINT HARENVREP_ENVID_FK
 FOREIGN KEY (ENVOBJID)
  REFERENCES HARENVIRONMENT(ENVOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARENVREPOSITORY ADD CONSTRAINT HARENVREP_REPID_FK
 FOREIGN KEY (REPOSITOBJID)
  REFERENCES HARREPOSITORY(REPOSITOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARENVUSERLIST ADD CONSTRAINT HARENVUSERLIST_ENVID_FK
 FOREIGN KEY (ENVOBJID)
  REFERENCES HARENVIRONMENT(ENVOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARFILEEXTENSION ADD CONSTRAINT HARFILEEXTENSION_REPID_FK
 FOREIGN KEY (REPOSITOBJID)
  REFERENCES HARREPOSITORY(REPOSITOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARFORM ADD CONSTRAINT HARFORM_FTID_FK
 FOREIGN KEY (FORMTYPEOBJID)
  REFERENCES HARFORMTYPE(FORMTYPEOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARFORMHISTORY ADD CONSTRAINT HARFRMHST_FRMID_FK
 FOREIGN KEY (FORMOBJID)
  REFERENCES HARFORM(FORMOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARFORMTYPEDEFS ADD CONSTRAINT HARFTDEFS_FTID_FK
 FOREIGN KEY (FORMTYPEOBJID)
  REFERENCES HARFORMTYPE(FORMTYPEOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARINTMRGPROC ADD CONSTRAINT IMP_SPID_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARITEM ADD CONSTRAINT HARITEM_PATHID_FK
 FOREIGN KEY (PATHOBJID)
  REFERENCES HARITEMPATH(PATHOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARITEMPATH ADD CONSTRAINT HARITEMPATH_PP_FK
 FOREIGN KEY (PARENTPATHID)
  REFERENCES HARITEMPATH(PATHOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARITEMPATH ADD CONSTRAINT HARITEMPATH_REP_FK
 FOREIGN KEY (REPOSITOBJID)
  REFERENCES HARREPOSITORY(REPOSITOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARLINKEDPROCESS ADD CONSTRAINT HARLINKPRO_SPID_FK
 FOREIGN KEY (STATEOBJID, PARENTPROCOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARLINKEDPROCESS ADD CONSTRAINT HARLINKPRO_STID_FK
 FOREIGN KEY (STATEOBJID)
  REFERENCES HARSTATE(STATEOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARLISTDIFFPROC ADD CONSTRAINT HARLDP_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/



ALTER TABLE HARLISTVERSPROC ADD CONSTRAINT HARLVPROC_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARMERGEDVERSION ADD CONSTRAINT HARMRGVER_FK
 FOREIGN KEY (VERSIONOBJID)
  REFERENCES HARVERSION(VERSIONOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARMOVEPKGPROC ADD CONSTRAINT HARMVPKGPR_SPID_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARMVIEWITEMPATH ADD CONSTRAINT HARMVIPATH_PATH_FK
 FOREIGN KEY (PATHOBJID)
  REFERENCES HARITEMPATH(PATHOBJID)
  ON DELETE CASCADE

/



ALTER TABLE HARNOTIFY ADD CONSTRAINT HARNOTIFY_LKPID_FK
 FOREIGN KEY (PARENTPROCOBJID, PROCESSOBJID)
  REFERENCES HARLINKEDPROCESS(PARENTPROCOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARNOTIFY ADD CONSTRAINT HARNOTIFY_STPID_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARNOTIFYLIST ADD CONSTRAINT HARNOTLST_LPIDS_FK
 FOREIGN KEY (PARENTPROCOBJID, PROCESSOBJID)
  REFERENCES HARLINKEDPROCESS(PARENTPROCOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/



ALTER TABLE HARNOTIFYLIST ADD CONSTRAINT HARNOTLST_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARNOTIFYLIST ADD CONSTRAINT HARNOTLST_UGID_FK
 FOREIGN KEY (USRGRPOBJID)
  REFERENCES HARUSERGROUP(USRGRPOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARNOTIFYLIST ADD CONSTRAINT HARNOTLST_USRID_FK
 FOREIGN KEY (USROBJID)
  REFERENCES HARUSER(USROBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARPACKAGE ADD CONSTRAINT HARPKG_ENVID_FKEY
 FOREIGN KEY (ENVOBJID)
  REFERENCES HARENVIRONMENT(ENVOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARPACKAGEGROUP ADD CONSTRAINT HARPKGGRP_ENVID_FK
 FOREIGN KEY (ENVOBJID)
  REFERENCES HARENVIRONMENT(ENVOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARPATHFULLNAME ADD CONSTRAINT HPFN
 FOREIGN KEY (PATHOBJID)
  REFERENCES HARITEMPATH(PATHOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARPKGSINPKGGRP ADD CONSTRAINT HARPKGINPG_PGID_FK
 FOREIGN KEY (PKGGRPOBJID)
  REFERENCES HARPACKAGEGROUP(PKGGRPOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARPKGSINPKGGRP ADD CONSTRAINT HARPKGSINPG_PID_FK
 FOREIGN KEY (PACKAGEOBJID)
  REFERENCES HARPACKAGE(PACKAGEOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARPROJECTATTR ADD CONSTRAINT HPA
 FOREIGN KEY (VERSIONOBJID)
  REFERENCES HARVERSION(VERSIONOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARPROMOTEPROC ADD CONSTRAINT HARPRO_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARREMITEMPROC ADD CONSTRAINT HARRIP_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARREPVIEWPATH ADD CONSTRAINT RVP_FK
 FOREIGN KEY (PATHOBJID)
  REFERENCES HARITEMPATH(PATHOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARREPVIEWPATH ADD CONSTRAINT VIP_FK
 FOREIGN KEY (REPVIEWOBJID)
  REFERENCES HARREPVIEW(REPVIEWOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARREPVIEWVERSION ADD CONSTRAINT RVV1_FK
 FOREIGN KEY (VERSIONOBJID)
  REFERENCES HARVERSION(VERSIONOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARREPVIEWVERSION ADD CONSTRAINT RVV2_FK
 FOREIGN KEY (REPVIEWOBJID)
  REFERENCES HARREPVIEW(REPVIEWOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARSNAPVIEWPROC ADD CONSTRAINT HARSVPROC_SPIDS_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARSTATE ADD CONSTRAINT HARSTATE_ENVID_FK
 FOREIGN KEY (ENVOBJID)
  REFERENCES HARENVIRONMENT(ENVOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARSTATE ADD CONSTRAINT HARSTATE_VIEWID_FK
 FOREIGN KEY (VIEWOBJID)
  REFERENCES HARVIEW(VIEWOBJID)

/


ALTER TABLE HARSTATE ADD CONSTRAINT HARSTATE_PM_FK
 FOREIGN KEY (PMSTATUSINDEX)
  REFERENCES HARPMSTATUS(PMSTATUSINDEX)

/


ALTER TABLE HARSTATEPROCESS ADD CONSTRAINT HARSTATEPROC_ST_FK
 FOREIGN KEY (STATEOBJID)
  REFERENCES HARSTATE(STATEOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARUDP ADD CONSTRAINT HARUDP_LNKPROID_FK
 FOREIGN KEY (PARENTPROCOBJID, PROCESSOBJID)
  REFERENCES HARLINKEDPROCESS(PARENTPROCOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARUDP ADD CONSTRAINT HARUDP_STPROCID_FK
 FOREIGN KEY (STATEOBJID, PROCESSOBJID)
  REFERENCES HARSTATEPROCESS(STATEOBJID, PROCESSOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARUSERSINGROUP ADD CONSTRAINT HARUSRSGRP_UGID_FK
 FOREIGN KEY (USRGRPOBJID)
  REFERENCES HARUSERGROUP(USRGRPOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARUSERSINGROUP ADD CONSTRAINT HARUSRSGRP_USER_FK
 FOREIGN KEY (USROBJID)
  REFERENCES HARUSER(USROBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVERSION ADD CONSTRAINT HARVERSION_EID_FK
 FOREIGN KEY (ENVOBJID)
  REFERENCES HARENVIRONMENT(ENVOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVERSION ADD CONSTRAINT HARVERSION_ITEM_FK
 FOREIGN KEY (ITEMOBJID)
  REFERENCES HARITEM(ITEMOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVERSIONINVIEW ADD CONSTRAINT VIV1_FK
 FOREIGN KEY (VERSIONOBJID)
  REFERENCES HARVERSION(VERSIONOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVERSIONINVIEW ADD CONSTRAINT VIV2_FK
 FOREIGN KEY (VIEWOBJID)
  REFERENCES HARVIEW(VIEWOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVIEW ADD CONSTRAINT HARVIEW_FKEY
 FOREIGN KEY (ENVOBJID)
  REFERENCES HARENVIRONMENT(ENVOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVIEWSOFREP ADD CONSTRAINT HARVOFR1_FK
 FOREIGN KEY (REPOSITOBJID)
  REFERENCES HARREPOSITORY(REPOSITOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVIEWSOFREP ADD CONSTRAINT HARVOFR2_FK
 FOREIGN KEY (REPVIEWOBJID)
  REFERENCES HARREPVIEW(REPVIEWOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVIEWVERSION ADD CONSTRAINT VV1_FK
 FOREIGN KEY (VERSIONOBJID)
  REFERENCES HARVERSION(VERSIONOBJID)
  ON DELETE CASCADE

/


ALTER TABLE HARVIEWVERSION ADD CONSTRAINT VV2_FK
 FOREIGN KEY (VIEWOBJID)
  REFERENCES HARVIEW(VIEWOBJID)
  ON DELETE CASCADE

/

/* 
 * Add constraints that were introduced in Harvest 5 
 */
ALTER TABLE HARVERSION ADD CONSTRAINT HARVERSIONS_PKGID_FK
 FOREIGN KEY (PACKAGEOBJID)
  REFERENCES HARPACKAGE(PACKAGEOBJID)

/

ALTER TABLE HARASSOCPKG ADD CONSTRAINT HARASSOCPKG_AID_FK
 FOREIGN KEY (ASSOCPKGID)
  REFERENCES HARPACKAGE(PACKAGEOBJID)
  ON DELETE CASCADE

/

/* Make sure all child form tables reference harForm */ 
START FormConstraintsSlave.sql

spool off
exit


