rmdir /s /q D:\0ab7c28d2ce71f5e7b1012
rmdir /s /q D:\b
rmdir /s /q D:\Binaries
rmdir /s /q D:\BuildDownloads
rmdir /s /q D:\downloader
rmdir /s /q D:\iSense
rmdir /s /q D:\iSenseAgent
rmdir /s /q D:\iSenseManager
rmdir /s /q D:\iSenseRemote
rmdir /s /q D:\iSenseRestore
rmdir /s /q D:\iSenseTray
rmdir /s /q D:\iXMedia
rmdir /s /q D:\Main.DailyBuild
rmdir /s /q D:\nbase
rmdir /s /q D:\NBaseMigration
rmdir /s /q D:\nchevron
rmdir /s /q D:\nmap
rmdir /s /q D:\NMC
rmdir /s /q D:\Nucleus9
rmdir /s /q D:\PowerGUI
rmdir /s /q D:\rubish
rmdir /s /q D:\sdks
rmdir /s /q D:\Security
rmdir /s /q D:\TARGET
rmdir /s /q D:\Test
rmdir /s /q D:\TFS
rmdir /s /q D:\TFS_Builds
rmdir /s /q D:\TFSBuild_Source\e
rmdir /s /q D:\TFSBuild_Source\Fusion6000
rmdir /s /q D:\TFSBuild_Source\Nucleus
rmdir /s /q D:\TFSBuild_Source\Payment
rmdir /s /q D:\TFSBuild_Source\PetronasOPT
rmdir /s /q D:\TFSBuild_Source\Nucleus\Chevron-Dev
rmdir /s /q D:\TFSBuild_Source\Nucleus\Chevron-Release
rmdir /s /q D:\TFSBuild_Source\Nucleus\Dev-Heartland-600
rmdir /s /q D:\TFSBuild_Source\Nucleus\FD0800_Dev
rmdir /s /q D:\TFSBuild_Source\Nucleus\GenPOS_Fullup_ATX
rmdir /s /q D:\TFSBuild_Source\Nucleus\GenPOS_Fullup_OP1
rmdir /s /q D:\TFSBuild_Source\Nucleus\GenPOS_Fullup_OP2
rmdir /s /q D:\TFSBuild_Source\Nucleus\GenPOS_Fullup_SH
rmdir /s /q D:\TFSBuild_Source\Nucleus\GenPOS_Main
rmdir /s /q D:\TFSBuild_Source\Nucleus\GenPOS_NucLite
rmdir /s /q D:\TFSBuild_Source\Nucleus\GenPOS_NucLite_LPR1
rmdir /s /q D:\TmpInclude
rmdir /s /q D:\Tools
rmdir /s /q D:\WAYNE
rmdir /s /q D:\WayneDB
rmdir /s /q D:\WORK

