Find /I "HR-Reports-2003" catch.bat >> found
Find /I "HR-Reports-2003" files.ext >> found
Find /I "HR-Reports-2003" grabHrFunctionsDll.pl >> found
Find /I "HR-Reports-2003" hrReportsDllCkIn.pl >> found
Find /I "HR-Reports-2003" hrReportsDllCkOut.pl >> found
Find /I "HR-Reports-2003" hrReportsExecBld.pl >> found
Find /I "HR-Reports-2003" hrReportsFormalBld.pl >> found
Find /I "HR-Reports-2003" hrReportsGenBld.pl >> found
Find /I "HR-Reports-2003" hrReportsWebCheck.pl >> found
Find /I "HR-Reports-2003" hrreportsWebDllBld.bat >> found
Find /I "HR-Reports-2003" massWebCheck.bat >> found
Find /I "HR-Reports-2003" myHRReportsLinkChecker.pl >> found
Find /I "HR-Reports-2003" omWebDllBld.bat >> found
Find /I "HR-Reports-2003" setRead-Only.pl >> found
Find /I "HR-Reports-2003" unsetRead-Only.pl >> found
Find /I "HR-Reports-2003" unsetRead.bat >> found
Find /I "HR-Reports-2003" updateHrReports.pl >> found
Find /I "HR-Reports-2003" webCheck.bat >> found
