hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del CSA.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\3rdparty\stdalone" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del CSA.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del CSA.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del CmpCrmf.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del IBMKeyManagementServer.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del US_export_policy.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\security" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del adxlib.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ad\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del akobjnav.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ak\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del asg.jar -rp "\Oracle eBusiness Suite\appl\asg\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del asg.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\asg\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del asgmaf.jar -rp "\Oracle eBusiness Suite\appl\asg\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del asgmaf.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\asg\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del asgmtran.jar -rp "\Oracle eBusiness Suite\appl\asg\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del asgmtran.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\asg\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del asthgrid.jar -rp "\Oracle eBusiness Suite\appl\ast\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del asthgrid.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ast\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del astiesbn.jar -rp "\Oracle eBusiness Suite\appl\ast\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del astiesbn.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ast\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del astuijav.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ast\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del astuijav.jar -rp "\Oracle eBusiness Suite\appl\ast\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del azwizard.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\az\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del azwizard.jar -rp "\Oracle eBusiness Suite\appl\az\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bomjar.jar -rp "\Oracle eBusiness Suite\appl\bom\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bomjar.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\bom\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bpel_PO_PoSendPoToOtm_1_0.jar -rp "\Oracle eBusiness Suite\appl\po\12.0.0\patch\115\jar\bpel" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bpel_wsh_ReceivePShipmentFromOtm_1_0.jar -rp "\Oracle eBusiness Suite\appl\wsh\12.0.0\patch\115\jar\bpel" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bpel_wsh_SendDlvyToOtmService_1_0.jar -rp "\Oracle eBusiness Suite\appl\wsh\12.0.0\patch\115\jar\bpel" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bpel_wsh_SendItemRefDataToOtm_1_0.jar -rp "\Oracle eBusiness Suite\appl\wsh\12.0.0\patch\115\jar\bpel" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bpel_wsh_SendLocRefDataToOtm_1_0.jar -rp "\Oracle eBusiness Suite\appl\wsh\12.0.0\patch\115\jar\bpel" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bpel_wsh_SendRefDataStlToOtm_1_0.jar -rp "\Oracle eBusiness Suite\appl\wsh\12.0.0\patch\115\jar\bpel" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bpel_wsh_SendTripToOtmService_1_0.jar -rp "\Oracle eBusiness Suite\appl\wsh\12.0.0\patch\115\jar\bpel" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del bpel_wsh_SendTxnToOtmService_1_0.jar -rp "\Oracle eBusiness Suite\appl\wsh\12.0.0\patch\115\jar\bpel" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctbasic.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cct\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctbasic.jar -rp "\Oracle eBusiness Suite\appl\cct\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctnet.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cct\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctnet.jar -rp "\Oracle eBusiness Suite\appl\cct\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctotm.jar -rp "\Oracle eBusiness Suite\appl\cct\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctotm.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cct\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctroute.jar -rp "\Oracle eBusiness Suite\appl\cct\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctroute.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cct\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctsoft.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cct\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cctsoft.jar -rp "\Oracle eBusiness Suite\appl\cct\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del charsets.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del core.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cs.jar -rp "\Oracle eBusiness Suite\appl\cs\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cs.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cs\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csc.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\csc\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csc.jar -rp "\Oracle eBusiness Suite\appl\csc\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csfchart.jar -rp "\Oracle eBusiness Suite\appl\csf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csfchart.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\csf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csfemap.jar -rp "\Oracle eBusiness Suite\appl\csf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csfemap.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\csf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csflf.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\csf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csflf.jar -rp "\Oracle eBusiness Suite\appl\csf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csfmdg.jar -rp "\Oracle eBusiness Suite\appl\csf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csfmdg.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\csf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csftds.jar -rp "\Oracle eBusiness Suite\appl\csf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csftds.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\csf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csfwap.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\csf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csfwap.jar -rp "\Oracle eBusiness Suite\appl\csf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csrclient.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\csr\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del csrclient.jar -rp "\Oracle eBusiness Suite\appl\csr\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ctoispproc.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\bom\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ctoispproc.jar -rp "\Oracle eBusiness Suite\appl\bom\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del czclient.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cz\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del czclient.jar -rp "\Oracle eBusiness Suite\appl\cz\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del czdb.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cz\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del czdb.jar -rp "\Oracle eBusiness Suite\appl\cz\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cztag.jar -rp "\Oracle eBusiness Suite\appl\cz\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del cztag.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\cz\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del deploy.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del dt.jar -rp "\Oracle eBusiness Suite\util\jdk\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del dtfj-interface.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del dtfj.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del eampmsch.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\eam\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del eampmsch.jar -rp "\Oracle eBusiness Suite\appl\eam\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del eamwkbch.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\eam\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del eamwkbch.jar -rp "\Oracle eBusiness Suite\appl\eam\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ecxprocess.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ecx\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ecxprocess.jar -rp "\Oracle eBusiness Suite\appl\ecx\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ecxutils.jar -rp "\Oracle eBusiness Suite\appl\ecx\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ecxutils.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ecx\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fiifdhm.jar -rp "\Oracle eBusiness Suite\appl\fii\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fiifdhm.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fii\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del flmkbn.jar -rp "\Oracle eBusiness Suite\appl\flm\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del flmkbn.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\flm\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del flmmmm.jar -rp "\Oracle eBusiness Suite\appl\flm\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del flmmmm.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\flm\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del flmrtg.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\flm\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del flmrtg.jar -rp "\Oracle eBusiness Suite\appl\flm\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndactiv.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndactiv.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndactiv.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaoam.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaoam.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaoam.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaol.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaol.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaol.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaolj.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaolj.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaolj.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaroraclnt.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaroraclnt.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndaroraclnt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbalishare.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbalishare.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbalishare.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbicmn-nls.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbicmn-nls.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbicmn-nls.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbicmn.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbicmn.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbicmn.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbipres-nls.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbipres-nls.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbipres-nls.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbipres.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbipres.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndbipres.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcct.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcct.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcct.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcollections.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcollections.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcollections.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndconnectionmanager.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndconnectionmanager.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndconnectionmanager.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcp.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcp.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndcp.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndctx.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndctx.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndctx.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddacf.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddacf.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddacf.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddb.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddb.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddb.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddpx20.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddpx20.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddpx20.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndds.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndds.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndds.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssdataview.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssdataview.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssdataview.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssgraph.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssgraph.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssgraph.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssgraphgui.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssgraphgui.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssgraphgui.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddsspfj.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddsspfj.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddsspfj.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssrules.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssrules.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssrules.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssutil.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssutil.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssutil.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssutilgui.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssutilgui.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fnddssutilgui.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndewt.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndewt.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndewt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndewtpv.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndewtpv.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndewtpv.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndext.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndext.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndext.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndforms.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndforms.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndforms.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndformsi18n.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndformsi18n.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndformsi18n.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndfsec.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndfsec.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndfsec.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndgantt.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndgantt.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndgantt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndgraphbuilder.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndgraphbuilder.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndgraphbuilder.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhelp.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhelp.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhelp.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhelpc.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhelpc.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhelpc.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhier.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhier.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndhier.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndicebrwsr.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndicebrwsr.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndicebrwsr.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndinfobus.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndinfobus.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndinfobus.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjewt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjewt.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjewt.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjewtall.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjewtall.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjewtall.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjgl.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjgl.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjgl.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjle.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjle.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjle.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjndi.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjndi.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndjndi.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndlist.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndlist.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndlist.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndlrucache.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndlrucache.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndlrucache.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndmail.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndmail.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndmail.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndmxt20.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndmxt20.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndmxt20.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndnetcharts.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndnetcharts.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndnetcharts.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndoam.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndoam.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndoam.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndoid.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndoid.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndoid.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndpromise.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndpromise.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndpromise.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndprospect.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndprospect.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndprospect.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndrt.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndrt.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndrt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndsec.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndsec.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndsec.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndswing.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndswing.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndswing.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndswingall.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndswingall.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndswingall.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtcf.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtcf.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtcf.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtdg.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtdg.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtdg.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtsgraph.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtsgraph.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndtsgraph.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndutil.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndutil.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndutil.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndvbj.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndvbj.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndvbj.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndxmlparserv2.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndxmlparserv2.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fndxmlparserv2.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fwk_client.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fwk_client.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del fwk_client.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del glahelcl.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\gl\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del glahelcl.jar -rp "\Oracle eBusiness Suite\appl\gl\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del glfdhm.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\gl\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del glfdhm.jar -rp "\Oracle eBusiness Suite\appl\gl\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del glgcs.jar -rp "\Oracle eBusiness Suite\appl\gl\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del glgcs.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\gl\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del gmddesg.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\gmd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del gmddesg.jar -rp "\Oracle eBusiness Suite\appl\gmd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del gmegantt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\gme\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del gmegantt.jar -rp "\Oracle eBusiness Suite\appl\gme\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del graphics.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del gskikm.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del htmlconverter.jar -rp "\Oracle eBusiness Suite\util\jdk\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmcertpathprovider.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmcfw.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmcmsprovider.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmjaaslm.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmjcefips.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmjcefw.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmjceprovider.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmjgssprovider.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmjsseprovider2.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmkeycert.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmorb.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmorbapi.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmpkcs.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmpkcs11.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmpkcs11impl.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ibmsaslprovider.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iebMMSWBConnect.jar -rp "\Oracle eBusiness Suite\appl\ieb\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iebMMSWBConnect.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieb\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iebserver.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieb\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iebserver.jar -rp "\Oracle eBusiness Suite\appl\ieb\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iecdb.jar -rp "\Oracle eBusiness Suite\appl\iec\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iecdb.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\iec\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieologger.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieo\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieologger.jar -rp "\Oracle eBusiness Suite\appl\ieo\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieoutil.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieo\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieoutil.jar -rp "\Oracle eBusiness Suite\appl\ieo\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iesauthr.jar -rp "\Oracle eBusiness Suite\appl\ies\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iesauthr.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ies\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iesclien.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ies\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iesclien.jar -rp "\Oracle eBusiness Suite\appl\ies\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iescommn.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ies\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iescommn.jar -rp "\Oracle eBusiness Suite\appl\ies\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iesservr.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ies\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iesservr.jar -rp "\Oracle eBusiness Suite\appl\ies\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuagent.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuagent.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuclient.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuclient.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieucommon.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieucommon.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuctrl.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuctrl.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieulog.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieulog.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieunet.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieunet.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieustuba.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieustuba.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieusvrlet.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieusvrlet.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuui.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuui.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuutil.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\ieu\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ieuutil.jar -rp "\Oracle eBusiness Suite\appl\ieu\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iexbeans.jar -rp "\Oracle eBusiness Suite\appl\iex\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iexbeans.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\iex\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iexdbjav.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\iex\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del iexdbjav.jar -rp "\Oracle eBusiness Suite\appl\iex\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del indicim.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del invdbtrx.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\inv\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del invdbtrx.jar -rp "\Oracle eBusiness Suite\appl\inv\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del invlabel.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\inv\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del invlabel.jar -rp "\Oracle eBusiness Suite\appl\inv\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jaccess.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jardiff.jar -rp "\Oracle eBusiness Suite\util\jdk\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del javaplugin.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del javaws.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jbodatum111.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\3rdparty\stdalone" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jbodatum111.jar -rp "\Oracle eBusiness Suite\java\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jbodomorcl.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jbodomorcl.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jbodomorcl.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jboremote.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jboremote.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jboremote.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jbovbclient.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jbovbclient.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jbovbclient.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jdev-rt.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jdev-rt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jdev-rt.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jdmpview.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\ext" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jnlp-servlet.jar -rp "\Oracle eBusiness Suite\util\jdk\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jnlp.jar -rp "\Oracle eBusiness Suite\util\jdk\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtffms.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\jtf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtffms.jar -rp "\Oracle eBusiness Suite\appl\jtf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfgantt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\jtf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfgantt.jar -rp "\Oracle eBusiness Suite\appl\jtf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfgrid.jar -rp "\Oracle eBusiness Suite\appl\jtf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfgrid.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\jtf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfpub.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\jtf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfpub.jar -rp "\Oracle eBusiness Suite\appl\jtf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfscgnt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\jtf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfscgnt.jar -rp "\Oracle eBusiness Suite\appl\jtf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfsub.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\jtf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfsub.jar -rp "\Oracle eBusiness Suite\appl\jtf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfui.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\jtf\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del jtfui.jar -rp "\Oracle eBusiness Suite\appl\jtf\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del lms.jar -rp "\Oracle eBusiness Suite\webapps\oacore\html" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del local_policy.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib\security" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mapclient.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mapclient.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mapclient.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mrpjar.jar -rp "\Oracle eBusiness Suite\appl\mrp\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mrpjar.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\mrp\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mscconnector.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\msc\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mscconnector.jar -rp "\Oracle eBusiness Suite\appl\msc\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mscjar.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\msc\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mscjar.jar -rp "\Oracle eBusiness Suite\appl\msc\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del msdjar.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\msd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del msdjar.jar -rp "\Oracle eBusiness Suite\appl\msd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del msejar.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\msd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mstjar.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\mst\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del mstjar.jar -rp "\Oracle eBusiness Suite\appl\mst\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del payproc.jar -rp "\Oracle eBusiness Suite\appl\pay\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del payproc.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\pay\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del payutil.jar -rp "\Oracle eBusiness Suite\appl\pay\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del payutil.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\pay\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del peradmin.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\per\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del peradmin.jar -rp "\Oracle eBusiness Suite\appl\per\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del performs.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\per\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del performs.jar -rp "\Oracle eBusiness Suite\appl\per\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perimage.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\per\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perimage.jar -rp "\Oracle eBusiness Suite\appl\per\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perkigfclient.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\per\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perkigfclient.jar -rp "\Oracle eBusiness Suite\appl\per\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perkpiclient.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\per\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perkpiclient.jar -rp "\Oracle eBusiness Suite\appl\per\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perkpimod01.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\per\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perkpimod01.jar -rp "\Oracle eBusiness Suite\appl\per\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perkpiserver.jar -rp "\Oracle eBusiness Suite\appl\per\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del perkpiserver.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\per\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ponam.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\pon\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del ponam.jar -rp "\Oracle eBusiness Suite\appl\pon\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del qa.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\qa\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del qa.jar -rp "\Oracle eBusiness Suite\appl\qa\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del security.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del server.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del tools.jar -rp "\Oracle eBusiness Suite\util\jdk\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del vea.jar -rp "\Oracle eBusiness Suite\appl\vea\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del vea.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\vea\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del vm.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfapi.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfapi.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfapi.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfbes.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfbes.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfbes.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wffrm.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wffrm.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wffrm.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfjava.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfjava.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfjava.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfmon.jar -rp "\Oracle eBusiness Suite\comn\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfmon.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\fnd\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wfmon.jar -rp "\Oracle eBusiness Suite\appl\fnd\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wipgantt.jar -rp "\Oracle eBusiness Suite\appl\wip\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wipgantt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wip\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wipmedia.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wip\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wipmedia.jar -rp "\Oracle eBusiness Suite\appl\wip\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wipopdep.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wip\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wipopdep.jar -rp "\Oracle eBusiness Suite\appl\wip\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wippcb.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wip\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wippcb.jar -rp "\Oracle eBusiness Suite\appl\wip\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wipssui.jar -rp "\Oracle eBusiness Suite\appl\wip\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wipssui.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wip\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wiputil.jar -rp "\Oracle eBusiness Suite\appl\wip\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wiputil.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wip\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wma.jar -rp "\Oracle eBusiness Suite\appl\wip\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wma.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wip\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wmscrtzn.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wms\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wmscrtzn.jar -rp "\Oracle eBusiness Suite\appl\wms\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wmsjar.jar -rp "\Oracle eBusiness Suite\appl\wms\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wmsjar.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wms\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wpsgantt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wps\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wpsgantt.jar -rp "\Oracle eBusiness Suite\appl\wps\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wpspref.jar -rp "\Oracle eBusiness Suite\appl\wps\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del wpspref.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\wps\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del xdpclnt.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\xdp\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del xlatacct.jar -rp "\Oracle eBusiness Suite\appl\xla\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del xlatacct.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\xla\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del xml.jar -rp "\Oracle eBusiness Suite\util\jdk\jre\lib" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del xtrintrp.jar -rp "\Oracle eBusiness Suite\appl\xtr\12.0.0\java\jar" -oa log\blowtorchJars.log
hrepmngr -b DEVSWA -eh AndrewsMic.dfo -del xtrintrp.jar -rp "\Oracle eBusiness Suite\java\classes\oracle\apps\xtr\jar" -oa log\blowtorchJars.log