hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\common\menu" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\login" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\common\asp" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\common\css" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\main" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\Mindleader" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\images" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\schedule" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\Mindleader\course_info" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\Mindleader\documents" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\_vti_pvt" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\admin\reports" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\common\java" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\images\exam_images" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\include" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\Mindleader\course_info\style" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\admin\reports\common\asp" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\course" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\Mindleader\course_info\images" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\error" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\exam" -oa logs\WBL_sccFiles.log -wts
hrepmngr -b PRODSWA -eh AndrewsMic.dfo -del "vssver.scc" -rp "\WBL\Mindleader\course_info\xml" -oa logs\WBL_sccFiles.log -wts
